"""
dxf_export.py — Convert a trimesh model into a DXF (R2018)
that opens natively in AutoCAD, Civil 3D, Revit, BricsCAD, Rhino, SketchUp,
Navisworks, and pretty much every CAD tool on earth.

DXF is the open, text-based sibling of DWG. AutoCAD's File > Save As lets you
convert DXF -> DWG in one click if you specifically need the binary format.
"""

import io
import ezdxf
from ezdxf.enums import TextEntityAlignment


# CDM Smith-aligned layer palette (short names, ACI colors)
LAYER_DEFS = [
    # (name, ACI color, lineweight_100umm, description)
    ("EQP_BODY",        7,   35, "Equipment body geometry"),
    ("EQP_FLANGE",      2,   25, "Flanges and end caps"),
    ("EQP_PIPE",        5,   25, "Connection pipes"),
    ("EQP_MOTOR",       4,   25, "Motor / driver"),
    ("EQP_ACCESSORY",   6,   18, "Accessories, doors, louvers"),
    ("EQP_LABEL",       3,    9, "Text labels and callouts"),
    ("EQP_METADATA",    8,    9, "Metadata block"),
]


def _ensure_layers(doc):
    """Create CDMS-style layers on the document."""
    for name, color, lw, desc in LAYER_DEFS:
        if name in doc.layers:
            continue
        layer = doc.layers.add(name)
        layer.color = color
        try:
            layer.dxf.lineweight = lw
        except Exception:
            pass
        layer.description = desc


def _add_mesh_as_polyface(msp, mesh, layer="EQP_BODY"):
    """Add a trimesh as a single 3D polyface mesh entity."""
    vertices = [tuple(float(x) for x in v) for v in mesh.vertices.tolist()]
    faces = [tuple(int(i) for i in f) for f in mesh.faces.tolist()]

    polymesh = msp.add_polyface(dxfattribs={"layer": layer})
    polymesh.append_faces(
        [[vertices[i] for i in face] for face in faces]
    )
    polymesh.optimize()
    return polymesh


def _add_title_block(msp, title, subtitle, meta_lines):
    """Small title block placed at world origin, below the model."""
    # Locate under the model bbox — placement handled by caller if needed
    x0, y0 = 0.0, -200.0
    box_w, box_h = 3200.0, 550.0

    # Frame
    msp.add_lwpolyline(
        [(x0, y0), (x0 + box_w, y0),
         (x0 + box_w, y0 - box_h), (x0, y0 - box_h),
         (x0, y0)],
        dxfattribs={"layer": "EQP_METADATA"},
        close=True,
    )
    # CDM Smith band
    msp.add_lwpolyline(
        [(x0, y0), (x0 + box_w, y0),
         (x0 + box_w, y0 - 90), (x0, y0 - 90),
         (x0, y0)],
        dxfattribs={"layer": "EQP_METADATA"},
        close=True,
    )
    msp.add_text(
        "CDM SMITH  |  CUTSHEET → 3D",
        dxfattribs={"layer": "EQP_LABEL", "height": 50.0},
    ).set_placement((x0 + 40, y0 - 60), align=TextEntityAlignment.LEFT)

    msp.add_text(
        title,
        dxfattribs={"layer": "EQP_LABEL", "height": 60.0},
    ).set_placement((x0 + 40, y0 - 170), align=TextEntityAlignment.LEFT)

    msp.add_text(
        subtitle,
        dxfattribs={"layer": "EQP_LABEL", "height": 35.0},
    ).set_placement((x0 + 40, y0 - 240), align=TextEntityAlignment.LEFT)

    y = y0 - 310
    for line in meta_lines:
        msp.add_text(
            line,
            dxfattribs={"layer": "EQP_METADATA", "height": 28.0},
        ).set_placement((x0 + 40, y), align=TextEntityAlignment.LEFT)
        y -= 42


def mesh_to_dxf_bytes(
    mesh,
    equipment_name="Equipment",
    manufacturer="",
    model_number="",
    properties=None,
):
    """
    Convert a trimesh into a DXF file (bytes).
    - Geometry goes on layer EQP_BODY as a 3D polyface mesh.
    - Title block + metadata table added below the model.
    """
    properties = properties or {}

    doc = ezdxf.new(dxfversion="R2018", setup=True)
    doc.units = ezdxf.units.MM
    doc.header["$INSUNITS"] = 4          # millimetres
    doc.header["$MEASUREMENT"] = 1       # metric
    _ensure_layers(doc)

    msp = doc.modelspace()

    # --- Add the geometry ---
    _add_mesh_as_polyface(msp, mesh, layer="EQP_BODY")

    # --- Title block ---
    meta_lines = [
        f"Manufacturer : {manufacturer or 'N/A'}",
        f"Model No.    : {model_number or equipment_name}",
        f"Generated by : Cutsheet-to-3D  (Arnab Mondal, CDM Smith BGA)",
    ]
    for k, v in properties.items():
        if v is None:
            continue
        pretty = str(k).replace("_", " ")
        meta_lines.append(f"{pretty:20s}: {v}")

    _add_title_block(
        msp,
        title=equipment_name.upper(),
        subtitle=f"{manufacturer}  {model_number}".strip(),
        meta_lines=meta_lines[:14],
    )

    # --- Attach properties as XDATA on the polyface ---
    # (survives round-trip through AutoCAD; visible via LIST or LISPy tools)
    doc.appids.add("CDMS_CUTSHEET")
    body_entities = [e for e in msp if e.dxf.layer == "EQP_BODY"]
    if body_entities:
        e = body_entities[0]
        xdata = [(1001, "CDMS_CUTSHEET"),
                 (1000, f"Equipment={equipment_name}"),
                 (1000, f"Manufacturer={manufacturer}"),
                 (1000, f"Model={model_number}")]
        for k, v in properties.items():
            if v is None:
                continue
            xdata.append((1000, f"{k}={v}"))
        try:
            e.set_xdata("CDMS_CUTSHEET", xdata)
        except Exception:
            pass

    # --- Serialise to bytes ---
    buf = io.StringIO()
    doc.write(buf)
    return buf.getvalue().encode("utf-8")
